### ISSUE TITLE
Issue with the permeability computation from IO.Statoil network 

### ISSUE THREAD

**Issue by mtembel** [PMEAL/OpenPNM#1146]
The Permeability calculation by OpenPNM seems to underestimate its actual value about 2 times compared to other codes; there's maybe a missing (x2) factor  somewhere in the code....I can't figure out where. 
Any suggestion?

**Comment by jgostick** [comment]
We've had this discussion before (#700) and I am sorry that it's still not fixed!  :-(

in V2 of OpenPNM we are trying to calculate the hydraulic conductances more accurately, but it is slightly incompatible with the old approach (our new uses more info about each pores and throat, including the ratio pore size to throat size).  I think the solution to this is to reintroduce a legacy version of the model, that is compatible with the more simple approach.  I will discuss with the group next week, but for now, consider making your own pore-scale model, that uses the equations you like?

**Comment by jgostick** [comment]
On the plus side, if you extract a network from Berea using SNOW in PoreSpy and run permeability on it in OpenPNM you get a terrific match!

**Comment by jgostick** [comment]
Not sure how long ago you used snow, or what branch, but at one point we added a much better surface / interface area calculation, using the marching cubes algorithm, and this slowed it down a lot. We since moved this out of snow and made it an optional thing for those who really need it.  Try downloading the dev branch and re-running snow.  400 cubed should only take a few minutes.  We've also added a way to put boundaries on the image BEFORE doing the extraction, so you get nice pores afterwards.  This will also be found in dev.  We are ramping up to a V1.0 release in early Jan, so stay posted.

**Comment by mtembel** [comment]
I am testing with dev branch. Still  the network extraction +  boundary conditions with a 3D image is not straightforward.  My first can be found [here](https://github.com/mtembel/TEST/blob/master/mTestPNM.ipynb)

**Comment by jgostick** [comment]
@Zohaib-Atiq can you look at @mtembel's code he linked to and let him know what's wrong?

**Comment by Zohaib-Atiq** [comment]
@mtembel 
1- Change the `dtype` of your image to `bool` before passing it to snow. You can do this by adding following line of code before extraction 
`im = numpy.array(im, dtype=bool)`
2- Use only `snow` if you want to calculate permeability in pore phase.
3- If you are using snow_advanced tutorial do not pass boundary_faces arg to `regions_to_network`. Boundary faces are added through separate method which we haven't updated in this tutorial yet. Use your first way of extraction by adding instructions of point 1 and you are good to go. 
I hope this helps. Let us know if you face any issue.

**Comment by mtembel** [comment]
@jgostick, for the sample provided, I got the following permeability(K) using different techniques 
-LBM 
K=1610 mD
-PNM
After extracting the network using maximal ball algo from Imperial college:
K=1153.29 mD  (from ICL)
K=1352 mD  Numscal (from  Heriot-Watt University)

**Comment by mtembel** [comment]
> Hi @mtembel I have been playing with your notebook and I think you have identified a bug. When we find the 'pore coordinate', we use the `center_of_mass` function in skimage. However, this is not necessarily the center of the pore according to the distance transform, so when we put the pore center at the center of mass and draw the inscribed sphere, it may be too large and overlap the neighboring pores. When I change the code to use the peak of the distance transform only 2 pores overlap (ie. negative throat lengths), instead of 161...i'd rather it be 0 pores overlapping though. When I subtract 1 voxel from the diameter of the pores before calculating the throat lengths, the I get 0 overlaps, so the 2 pores that do overlap are just barely overlapping. I will push this fix to dev asap.

Great for bug fix! Otherwise, I do use porespy -dev branch. The flexibility offered by openpnm will be quite attractive if it works.  Will try to dig deeper into the code, too.

**Comment by ma-sadeghi** [comment]
Hi @mtembel. I'm trying to reproduce the negative lengths you get, but for some reason, I can't. Do you use SNOW with default parameters?

**Comment by jgostick** [comment]
Hey all, I was able to see the negative throat lengths.  I pushed a fix, but I don't think i merged it yet.  @amin, there should be about 160 negative throats.

**Comment by ma-sadeghi** [comment]
@jgostick Yep, my bad. I can now reproduce the negative lengths.

**Comment by mtembel** [comment]
> Hi @mtembel. Are you sure the permeability is only off by a 2x factor? When I run your notebook with the latest OpenPNM and PoreSpy, I get something like 32,000 mD! Am I missing something?

@ma-sadeghi , sorry for my delayed response. Actually I got x2 factor only by running openpnm on a network extracted by ICL  maximum ball code--not with porespy...

**Comment by jgostick** [comment]
This is being addressed in detail by several more specific issues, so I'm going to close this one

**Comment by xu-kai-xu** [comment]
@jgostick, hi, jeff, I use PNM from ICL and calculate permeability as the IO tutorial, the results seem still different. The problem is still existing, is that right? I found the extracted PNM has a property `pore.clay_volume`. Is that possible the existance of clay components will narrow the flow channels so the permeability calculated by ICL is smaller than by OpenPNM?
