### ISSUE TITLE
Exporting to Statoil format

### ISSUE THREAD

**Issue by jhummel63** [PMEAL/OpenPNM#1210]
Hello,
I have seen that the statoil format is available for import. Is there any plan to support exporting an openpnm network to the statoil format?
I would like to visualize a network in avizo which supports the statoil format.
thanks a lot
best regards

**Comment by jgostick** [comment]
The statoil format is a mess!  It's 4 files with redundant info all over, and is poorly formatted.  I don't want to support export if at all possible...but I'm happy to support something else that Avizo can open.  I think @neumannrf created an issue suggesting that we export to PerGeos format....which I believe is the Avizo preferred or standard format?  Would this work for you?  Any chance you want to help contribute to this?  :-)

**Comment by jhummel63** [comment]
That would work even better yes! You are right, the am file format is the native one for both Avizo and Pergeos. I won't be able to help contributing but I can provide files example and explanations on how to support the format.

**Comment by jgostick** [comment]
Ok, file examples would be a great start.  Either attadh to this thread or send to me by email (jgostick at uwaterloo dot ca)

**Comment by neumannrf** [comment]
@jhummel63 I was willing to support @mbandreeta in the development of this extension, but we did not go far. Our goal was to provide some interoperability between the codes that each one of us uses. 
I cannot do it alone, for the simple fact that I down own a license for that commercial software, so I couldn't possibly test anything by myself.

**Comment by jgostick** [comment]
This is perfect then... @jhummel63 can supply us with an example file, @neumannrf and @jgostick can make the IO class, and @jhummel63 can test that it outputs a usable file.  When @jhummel63 sends me an example file, I'll forward it to you Rodrigo.

**Comment by jgostick** [comment]
I was in the mood to code tonight, so I actually wrote up save and load functions in a new PerGeos class.  I have pushed it to github and will make a PR.  @jhummel63 are you able to download this new code and try it out?  Or, perhaps I will load the files you sent me INTO openpnm, then back out to pergeos format, and send you the results to see if they open up in Avizo?  I got the formatting nearly identical, but there may be some whitespace issues, etc.

**Comment by jhummel63** [comment]
Great! yes please send me the results of the save function. I'll test if they can be loaded.
it's a minor detail but it would be best to call the class AmiraMesh. This is what am stands for and is the file format used by Avizo, Amira and PerGeos.

**Comment by jhummel63** [comment]
The attached file fixes the amira mesh save function, this includes all the basics for loading the file in avizo and allows saving any openpnm network. Still missing many openpnm parameters such as pore volume or throat length parameters...
[PerGeos.zip](https://github.com/PMEAL/OpenPNM/files/2855377/PerGeos.zip)
